version: '3.3'
services:

  db:
    image: mysql:5.7  
    container_name: car-pooling-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - car-pooling

  backend:
    image: ${BACKEND_IMAGE} 
    container_name: car-pooling-be
    ports:
      - '8088:8088'
    networks:
      - car-pooling
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db  

networks:
  car-pooling:
    driver: bridge

